### ISSUE TITLE
Some instructions for the flowchart

### ISSUE THREAD

**Issue by DataStrategist** [STATWORX/blog#1]
Hi, I love your https://github.com/STATWORX/blog/tree/master/flowchart it's really wonderful and what I've been looking for... however, I find the code a bit unexplained... I was wondering if you could perhaps add a bit more documentation, or perhaps just a small readme describing how to install or what functions to run. 

Of course I think it's also powerful enough to convert into a package, but that's neither here nor there :)

Thanks!

**Comment by Dschaykib** [comment]
Thanks :)
I will see what I can do over the weekend.

**Comment by DataStrategist** [comment]
Perfect. This is really useful! 

As a thanks, here's some improvements... adding interactivity thru the visnetwork package:


```
library(tidyverse)
library(visNetwork)

Expl <- net$matrix %>% mutate(FROM = rownames(net$matrix)) %>% gather(TO, Value, -FROM) %>% 
  filter(Value != 0)

nodes <- Expl$FROM %>% c(Expl$TO) %>% table %>% as_data_frame %>% rename(label = 1, value = n) %>% 
  mutate(id = 1:n())

edges <- Expl %>% left_join(nodes, c("FROM" = "label")) %>% rename(from = id) %>% select(-FROM) %>% 
  left_join(nodes, c("TO" = "label")) %>% rename(to = id) %>% select(-TO) %>% 
  mutate(arrows = "from")
  
visNetwork(nodes = nodes, edges = edges)

```

You can add it if you want... but this should be popularized sir! Blog about it more!

**Comment by DataStrategist** [comment]
Hi... did you delete my additional visNetwork code? Or did I fail to paste it?

**Comment by Dschaykib** [comment]
I did not delete anything on purpose. Which additional Code do you mean?
If you mean the one from above, I haven't checked that yet.

**Comment by DataStrategist** [comment]
Yeah, sorry about that, it was a refresh issue on my browser. :) It's just
the code above.
