### ISSUE TITLE
Filter data.table should not prevent optimizations

### ISSUE THREAD

**Issue by jangorecki** [STATWORX/blog#2]
Unfortunately link to GH repos in [this blog post](https://www.statworx.com/de/blog/pandas-vs-data-table-a-study-of-data-frames/) does not work anymore so I am filling issue here.

I briefly went trough the code of subset benchmark only and spotted potential issue in filtering queries. The way you are querying data.table makes it to fall back to data.frame way of doing subset. I am not sure if it makes big difference here, but it is definitely not the way to do that in data.table.
I explained this difference in "benchmarking best practices" document just now, you can preview it
https://github.com/Rdatatable/data.table/pull/3132/commits/2556b05a65c71aaca485aac3f53cf2908e5e6c8e

**Comment by tkrabel** [comment]
Thanks for the issue and the effort you put in to scan our code base. I will check it out soon. 
I will also take care of getting back the code to our first part of the simulation study. It's on a private repo right now.

Cheers

**Comment by tkrabel** [comment]
Fixed issue using `dt[eval(parse(...))]` logic
