### ISSUE TITLE
.py file doesn't match code from linked blog post

### ISSUE THREAD

**Issue by DavidLloydNGP** [STATWORX/blog#4]
Hi,

I found this project from a Statworx blog post:
[https://www.statworx.com/en/blog/how-to-build-a-dashboard-in-python-plotly-dash-step-by-step-tutorial/#contents](https://www.statworx.com/en/blog/how-to-build-a-dashboard-in-python-plotly-dash-step-by-step-tutorial/#contents)

It seems like the code referred to in the blog post is different to that in this repository. Perhaps an older version of the code is hosted here. Is there a python script available matching that shown in the blog post?

**Comment by Dschaykib** [comment]
I will have a look in the next days.

**Comment by Dschaykib** [comment]
It was just named incorrectly. I changed the name. Hope this helps you @DavidLloydNGP. If not, let me know.

**Comment by Dschaykib** [comment]
And for completeness, this is the folder for the blog post's example:
https://github.com/STATWORX/blog/tree/master/DashApp

**Comment by DavidLloydNGP** [comment]
Thanks for the quick reply.

Perhaps if I gave a concrete example my point would have been clearer.

On the blog post, the 'Layout' function has the following parameters:
'layout': 
`go.Layout(
                  colorway=["#5E0DAC", '#FF4F00', '#375CB1', '#FF7400', '#FFF400', '#FF0056'],
                  template='plotly_dark',
                  paper_bgcolor='rgba(0, 0, 0, 0)',
                  plot_bgcolor='rgba(0, 0, 0, 0)',
                  margin={'t': 50},
                  height=250,
                  hovermode='x',
                  autosize=True,
                  title={'text': 'Daily Change', 'font': {'color': 'white'}, 'x': 0.5},
                  xaxis={'showticklabels': False, 'range': [df_sub.index.min(), df_sub.index.max()]},
              )`

On github, the same function has different parameter values:
`go.Layout(
                  colorway=["#5E0DAC", '#FF4F00', '#375CB1', '#FF7400', '#FFF400', '#FF0056'],
                  template='plotly_dark',
                  paper_bgcolor='rgba(0, 0, 0, 0)',
                  plot_bgcolor='rgba(0, 0, 0, 0)',
                  margin={'b': 15},
                  hovermode='x',
                  autosize=True,
                  title={'text': 'Stock Prices', 'font': {'color': 'white'}, 'x': 0.5},
                  xaxis={'range': [df_sub.index.min(), df_sub.index.max()]},
              )`

Apologies if this seems needlessly pedantic. I am just starting out with Dash, and my dashboard doesn't look like the one in your blogpost, so I am keen to learn why. I think there may be other differences as well, which lead me to believe that the github file may be an older version of the code quoted in the blogpost.

**Comment by Dschaykib** [comment]
Ah ok. I will get in touch with the author and let him know :)

**Comment by DavidLloydNGP** [comment]
Thank you. Apologies for the long-winded description of a relatively simple problem.

**Comment by Dschaykib** [comment]
No problem, the long description made it perfectly clear what you meant!
And thanks for the feedback and spotting it!

**Comment by AlexanderBlaufuss** [comment]
Hi @DavidLloydNGP, 


thank you for bringing up the issue! I'm sure other readers were also wondering about the discrepancies between the blog and the .py file.

The app.py file should now work as intended and display the same results as shown in the screenshot of the blog.
I also made an update to import statements deprecated since dash v2.0. These changes, along with a different configuration of the Layout, are not (yet) included in the blog. Hopefully, I can find some time to make a larger update to the blog.


Thank you & have a great day!
Alex
